version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "webserve-sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-19dwg4zkoj97z"
s3_prefix = "webserve-sam-app"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

